.TH systemd-swap 8 "AUGUST 2020" "systemd-swap 4.4" systemd-swap
.SH NAME
systemd-swap \- Script for creating hybrid swap space from zram swaps, swap files and swap partitions.
.SH SYNOPSIS
.B systemd-swap [-h]
.I start|stop|status|compression
.SH DESCRIPTION
systemd-swap manages the configuration of
.B zram
and
.B zswap\fR,
allows for setting up swap files based on current memory usage through
.B swapfc
and allows for enabling existing swap files and partitions through
.B swapD\fR.
.SH OPTIONS
.IP start
Starts systemd-swap.
.IP stop
Stops systemd-swap.
.IP status
Prints the status of systemd-swap; modules being used and their statuses.
.IP compression
Prints compression algorithms currently loaded by the kernel.
.SH AUTHORS
Vilgot Fredenberg <vilgot@fredenberg.xyz>

Oliver Old <oliver.old@outlook.com>
.SH "SEE ALSO"
.BR swap.conf (5)
